version: '3'

services:
  db:
    image: postgres
    restart: always
    container_name: cflox_converter
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=cflox
    ports:
      - "5452:5432"